name: rice_quality_scaning_app
description: A new Flutter project.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  bloc: ^8.0.3
  camera: ^0.9.4+12
  cloud_firestore: ^3.1.5
  cupertino_icons: ^1.0.2
  email_validator: ^2.0.1
  equatable: ^2.0.3
  firebase_auth: ^3.3.7
  firebase_core: ^1.12.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_neumorphic: ^3.0.3
  google_fonts: ^2.3.1
  image_picker: ^0.8.4+8
  path: ^1.6.2
  path_provider: ^2.0.9

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  
  assets:
    - assets/images/
  